---
title: "devlog"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{devlog}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

```{r setup}
library(ggplot2)
library(dplyr)
library(ggstar)
```

```{r}
table <- read.table("inst/extdata/data.txt",header = T,stringsAsFactors = FALSE,sep = "\t")
table <- table %>% arrange(vip)
height = nrow(table)*1.1
pdf(width = 8.5,height = height)
n=3
ggplot(table,aes(x=forcats::fct_inorder(index),y=vip))+geom_point(color='darkblue',size=4*n)+coord_flip()+theme_void()+theme_linedraw(base_rect_size = 2*n)+theme( # remove the vertical grid lines
    panel.grid.major.x = element_blank() ,panel.grid.minor.x = element_blank() ,
    # explicitly set the horizontal lines (or they will disappear too)
    panel.grid.major.y = element_line( size=.5*n, color="black" ,linetype = "dashed") 
)+labs(x="",y="VIP")+ theme(text = element_text(size = 12*n))
dev.off()
```

```{r}
table2 <- read.table("../inst/extdata/8.txt",header = T,stringsAsFactors = FALSE,sep = "\t")
table2 <- table2 %>% arrange(Enrichment_Ratio)
n=2
pdf("8.pdf",width = 8.5,height = 11)
ggplot(table2,aes(x=forcats::fct_inorder(id),y=Enrichment_Ratio,fill=Raw_p,size=Enrichment_Ratio))+geom_star(show.legend = F)+coord_flip()+theme_void()+theme_linedraw(base_rect_size = 0.2*n)+theme( # remove the vertical grid lines
    panel.grid.major.x = element_blank() ,panel.grid.minor.x = element_blank() ,
    # explicitly set the horizontal lines (or they will disappear too)
    panel.grid.major.y = element_line( size=.1*n, color="grey" ,linetype = "dashed") 
)+labs(x="",y="Enrichment Ratio")+ theme(text = element_text(size = 12*n))+scale_fill_gradient(low="red", high="blue")+scale_size_continuous(range = c(4, 8))+ylim(2,9)
dev.off()
```

